<?php

namespace Modules\Student\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use \Modules\Base\Http\Controllers\AuthController as BaseAuth;

class AuthController extends BaseAuth
{
    public $guard = STUDENTS_GUARD;

    public $model = Student::class;

    public $redirectTo = 'student.dashboard.index';

    public $login_form = 'authentications.students.login';

    public function username()
    {
        return 'student_id'; // TODO: Change the autogenerated stub
    }

    public function showLoginForm()
    {
        if (auth()->guard($this->guard)->check())
            return redirect()->route($this->redirectTo);

        return view('authentications.students.login');
    }

}
