<?php

namespace Modules\Student\Http\Controllers;

use App\Models\StudentBalanceTransaction;
use Modules\Base\Http\Controllers\BaseController;
use Modules\Student\Http\Resources\StudentBalanceTransactionResource;

class StudentBalanceTransactionController extends BaseController
{

    protected $config = NO_ACTIONS_LIST;


    public function getQuery()
    {
        return parent::getQuery()->where('student_id',auth()->id()); // TODO: Change the autogenerated stub
    }
}
