<?php

namespace Modules\Student\Http\Controllers;

use App\Models\Course;
use App\Models\StudentCourse;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class StudentCourseController extends BaseController
{
    protected $config = array(
        'addBtn' => false,
        'editBtn' => false,
        'deleteBtn' => false,
        'deleteGroupAction' => false,
        'deleteAction' => false,
        'importBtn' => false,
        'trash' => false,
        'showAction' => false,
        'filter_inputs' => [
            [
                'type' => 'select',
                'model' => 'semester_id',
                'hideSearch' => true,
                'endpoint' => [
                    'option_value' => 'id',
                    'option_name' => 'title',
                    'model' => [
                        'function' => 'semesterOptions'
                    ]
                ],
            ],
        ]
    );

    public function getQuery()
    {

        $q = parent::getQuery(); // TODO: Change the autogenerated stub
        $requestValue = get(explode(',', get(request()->get('search'), 'value')), 1, null);
        $q->whereHas('course', function ($inner) use ($requestValue) {
            $inner->where('semester_id', $requestValue);
        });
        return $q;
    }
}
