<?php

namespace Modules\Teacher\Http\Controllers;

use App\Models\Student;
use App\Models\Teacher;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use \Modules\Base\Http\Controllers\AuthController as BaseAuth;

class AuthController extends BaseAuth
{
    public $guard = TEACHERS_GUARD;

    public $model = Teacher::class;

    public $redirectTo = 'teacher.dashboard.index';

    public $login_form = 'authentications.teachers.login';

    public function username()
    {
        return 'teacher_id'; // TODO: Change the autogenerated stub
    }

    public function showLoginForm()
    {
        if (auth()->guard($this->guard)->check())
            return redirect()->route($this->redirectTo);
        return view('authentications.teachers.login');
    }


}
