<?php

namespace Modules\Admin\Http\Controllers;

use App\Models\Admin;
use App\Models\Student;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use \Modules\Base\Http\Controllers\AuthController as BaseAuth;

class AuthController extends BaseAuth
{
    public $guard = ADMINS_GUARD;

    public $model = Admin::class;

    public $redirectTo = 'admin.dashboard.index';

    public $login_form = 'authentications.admins.login';

    public function username()
    {
        return 'email'; // TODO: Change the autogenerated stub
    }

    public function showLoginForm()
    {
        if (auth()->guard($this->guard)->check())
            return redirect()->route($this->redirectTo);
        return view('authentications.admins.login');
    }



}
