<?php

namespace Modules\Admin\Http\Controllers;

use App\Models\Student;
use App\Models\Teacher;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class NotificationController extends BaseController
{

    protected $config = [
        'editBtn' => false,
        'deleteBtn' => false,
    ];


    public function getAttributes($request)
    {
        $data = parent::getAttributes($request); // TODO: Change the autogenerated stub
        switch ($data['notification_type']){
            case 'teacher':
                $data['sourceable_model'] = Teacher::class;
                $data['sourceable_id'] = $data['teacher_id'];
                break;
            case 'student':
                $data['sourceable_model'] = Student::class;
                $data['sourceable_id'] = $data['student_id'];
                break;
            case 'students':
                $data['sourceable_model'] = Student::class;
                break;
            case 'teachers':
                $data['sourceable_model'] = Teacher::class;
                break;
        }
        return $data;
    }

}
