<?php

namespace Modules\Admin\Http\Controllers;

use App\Models\Student;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Admin\Http\Resources\StudentResource;
use Modules\Base\Http\Controllers\BaseController;

class StudentController extends BaseController
{
    public function getAttributes($request)
    {
        $data = parent::getAttributes($request); // TODO: Change the autogenerated stub
        if ($request->method() == 'POST')
          $data['student_id'] = '12023' . $request->get('student_id');
        return $data;
    }


    public function financialInfo($student_id)
    {
        $model = Student::where('student_id',$student_id)->first();
        $student = (new StudentResource($model))->serializeForFinancialInfo(\request());
        $view = view('admin.pages.financial.student_info',$student)->render();
        return response()->json(array('status' => true,'view' => $view));
    }




}
